tap "lawrence_danna/tap", "ssh://git@stash.sd.apple.com/~lawrence_danna/tap.git"
tap "homebrew/dupes"
tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"
brew "autoconf"
brew "automake"
brew "bash"
brew "bear"
brew "coreutils"
brew "findutils"
brew "gist"
brew "git-lfs"
brew "git-subrepo"
brew "grep"
brew "ispell"
brew "libidl"
brew "libtool"
brew "lynx"
brew "mas"
brew "parallel"
brew "python"
brew "python3"
brew "speedtest-cli"
brew "tig"
brew "truncate"
brew "wget"
brew "xhyve"
brew "youtube-dl"
brew "lawrence_danna/tap/rtags", args: ["HEAD"]
cask "alcatraz"
cask "macdown"
mas "Type2Phone", id: 472717129
