#!/usr/bin/perl -w




my $euid = $>;

my @repos = qw:
                bin
                config
                delicious
                gregarius
                gregarius-data
                lisp/lisputils
                maddox
                Pictures
                patches
                ronpaul
                slime
                lisp/blog
                crypto
                lulz
                notes
                public_html
                sbcl
                thepain  
                /var/www :; 

if ($euid == 0) {
  push @repos, qw: /etc/ /home/meghan/public_html :;
} else {
  print "NOT ROOT\n\n";
}


for $repo (@repos) {
  chdir '/home/larry' or die $!;
  chdir $repo or die $!; 
  my $out = `git status`; 
  if ($out !~ /nothing to commit \(working directory clean\)/) {
    print "******  $repo\n";
    print "============================================================\n";
    print "$out";
    print "============================================================\n\n";
  }
}

