#!/usr/bin/perl -w 


my $file;
my $tmp  = 0;

use Getopt::Long;
Getopt::Long::Configure ("bundling");
my ($diff);
GetOptions ("diff|d" => \$diff) or die "couln't get options $!";

if (@ARGV) { 
  $file = shift;
} else {
  $file = "/tmp/${$}eless";
  $tmp = 1;
  !(system "cat >$file") or die;
}

my $lisp = $diff ? 
    "(find-diff-file \"$file\")" :
    "(view-file \"$file\")";

!(system qw/ emacsclient -e /, $lisp)
  or !(system qw/ less -c /, $file)
  or die;

unlink $file if $tmp;

