#!/usr/bin/perl -w

$ENV{PATH} = $ENV{NOT_FUCKED_PATH};
  
my $file;
my $tmp  = 0;

use Getopt::Long;
Getopt::Long::Configure ("bundling");
my ($diff);
GetOptions ("diff|d" => \$diff) or die "couln't get options $!";

if (@ARGV) { 
  $file = shift;
} else {
  $file = "/tmp/${$}eless";
  $tmp = 1;
  open FH, ">$file" or die $!;
  while (<>) {
    print FH $_;
  }
  close FH;
}

my $lisp = $diff ? 
    "(find-diff-file \"$file\")" :
    "(view-file \"$file\")";


@command = (qw: emacsclient -a eless-alternate-editor --eval :, $lisp);

#print join(' ', map {"'$_'"} @command), "\n";

!(system @command)
  or $ENV{TERM} ne 'emacs' && !(system qw/ less -c /, $file)
  or die;

unlink $file if $tmp;

