#!/usr/bin/perl -w


for (@ARGV) {
    s/\\/\\\\/g;
    s/"/\\"/g;
}

my  $lisp  = <<"EOF";

(defun dmerge ()
  (interactive)
  (emerge-files-with-ancestor nil "$ARGV[0]" "$ARGV[1]" "$ARGV[2]" "$ARGV[3]")
  (window-configuration-to-register ?\j))

EOF

system 'emacsclient', '-e', $lisp;
