#!/bin/bash

case $1 in
    -*)
        dir=""
        ;;
    *) 
        dir=$1
        shift
        ;;
esac 
    


if [[ -z "$1" ]]; then
    foo=" -or -true "
else
    foo=" -or "
fi

find $dir \
         -name .git -prune   \
     -or -name .svn -prune   \
   $foo "$@"

