#!/usr/bin/python

import sys

def usage():
    print >>sys.stderr, "usage: flickr-date-fixer \"Album Name\" yyyy-mm-dd\n"
    sys.exit(1)

import flickrapi
import xml.etree
import dateutil.parser
import datetime
import time
import os
import json

with open(os.path.join(os.getenv("HOME"), ".flickr_key")) as f:
    keydict = json.load(f)

flickr = flickrapi.FlickrAPI(keydict['key'], keydict['secret'])
flickr.authenticate_via_browser(perms='write')

if not len(sys.argv) == 3:
    usage()

(name, date) = (unicode(sys.argv[1]), unicode(sys.argv[2]))

sets = flickr.photosets.getList()

assert sets.attrib['stat'] == 'ok'


def single(x):
    x = list(x)
    assert len(x) == 1
    return x[0]


s = single(x for x in sets.find('photosets').findall('photoset')
           if x.find('title').text == name)

#print xml.etree.ElementTree.tostring(s)

photos_res = flickr.photosets.getPhotos(
    extras='date_taken,date_upload',
    photoset_id=s.attrib['id'])
assert photos_res.attrib['stat'] == 'ok'

#print xml.etree.ElementTree.tostring(photos_res)

photos = photos_res.find('photoset').findall('photo')

#print xml.etree.ElementTree.tostring(photos[0])
#print repr(dateutil.parser.parse(photos[0].attrib['datetaken']))

for photo in photos:
    # d = dateutil.parser.parse(photo.attrib['datetaken'])
    d = dateutil.parser.parse(date)

    d = time.mktime(d.timetuple())
    #print d

    res = flickr.photos.setDates(photo_id = photo.attrib['id'],
                                 date_posted = d,
                                 date_taken = date)

    assert res.attrib['stat'] == 'ok'
