#!/usr/bin/perl -w

use File::Find;

sub wanted {
  return unless -f;
  return unless $_ eq ".cvsignore";
  my $fh;
  open $fh, "<", $_ or die $!;
  my $dir = $File::Find::dir;
  $dir =~ s/^\.\///;
  $dir =~ s/\/*$//;
   if ($dir eq '.') {
     $dir = '';
   } else {
     $dir .= '/';
   }
  while (<$fh>) {
    chomp;
    if (-d) {
      print "^${dir}$_\$\n";
      print "^${dir}$_/.*\$\n";
    } else {
      s/\./\\\./g; 
      s/\*/\.\*/g;
      print "^${dir}$_\$\n";
    }
    
  }
  close $fh;
}


print "syntax: regexp\n\n";
print '.*/CVS/.*', "\n";
print '.*\.fasl$', "\n";
print '.*\.o$', "\n";
print '.*~$', "\n";
  
find(\&wanted, ".");



