#!/usr/bin/perl -w

use IPC::Run qw/run/;

my $length = 15;
$length = shift if @ARGV;

my $pass;
run [qw/pwgen -1 --secure/, $length], '>', \$pass or die "pwgen failed\n";

$pass =~ s/\s*//g;

run [qw/xsel -i/], '<', \$pass or die "xsel failed\n";
run [qw/xsel -ib/], '<', \$pass or die "xsel failed\n";

print $pass, "\n";



  
