#!/usr/bin/perl -w 

use File::Temp qw/tempfile/;
use Getopt::Long;
Getopt::Long::Configure ("bundling");

my $permanant;
my $clear; 
GetOptions ( "permanant|p" => \$permanant,
             "clear|c"     => \$clear) or die "couln't get options $!";

system "rm -f $ENV{HOME}/.http-notification/notify.*" if $clear;

if (@ARGV) {
  my ($fh, $fn) = tempfile "notify.XXXXX", DIR => "$ENV{HOME}/.http-notification";
  $fh or die "can't generate tempfile: $!\n";

  print $fh join(',', @ARGV);
  close $fh; 

  unless ($permanant) {
    sleep 1;
    unlink $fn;
  }
}




  


