#!/usr/bin/perl -w  


use Getopt::Long; 
Getopt::Long::Configure ("bundling");

my $delim = q/\s+/;
my $field = 0;
my $chomp = 1;

GetOptions ("chomp|c=s" => sub { shift;
                                 my $x = shift;
                                 if       ($x eq 'no') {
                                   $chomp = 0;
                                 } elsif ($x eq 'yes') {
                                   $chomp = 1;
                                 } else {
                                   die "huh?";
                                 }
                               },
            "delimiter|d=s"  => \$delim,
            "field|f=s"  => \$field)
  or die "couldn't get options\n";


while (<>) {
  chomp if $chomp;
  @f = split $delim, $_;
  print $f[$field], "\n"; 
}
			



