#!/usr/bin/perl -w


use Email::LocalDelivery;
use Email::Folder;
use Email::Simple;
use Data::Dumper;
use Fcntl ':flock'; 
use Fcntl;


my $in = "$ENV{HOME}/mail/spam.new";
my $out = "$ENV{HOME}/mail/spam";


#$in = "$ENV{HOME}/mail/x";
#$out = "$ENV{HOME}/mail/y";

open $ifh, "+<$in"; 
open $ofh, ">>$out"; 

flock $ofh, LOCK_EX or die "can't acquire lock: $!"; 
flock $ifh, LOCK_EX or die "can't acquire lock: $!"; 

system "/usr/bin/spamprobe spam $in";
$? == 0 or die "spamprobe error!";

#seek $ofh, 0, SEEK_END or die "can't seek $!";

while (defined ($_ = <$ifh>)) {
  print $ofh $_;
}
truncate $ifh, 0 or die "can't truncate $!";

flock $ifh, LOCK_UN; 
flock $ofh, LOCK_UN; 

close $ifh;
close $ofh;





