#!/usr/bin/perl -w


my $divw = 200;
my $divh = 160;


use Getopt::Long;
Getopt::Long::Configure ("bundling");
my $fork;
GetOptions ("fork|f" => \$fork) or die "couln't get options $!";

my ($file, $out)  = @ARGV;

my $pid = $fork ? fork() : 0;

if ($pid) { 
  #parent
} else {
  if ($file =~ /\.mov$/i) { 
    my $tdir = "/tmp/mplayer_frames$$"; 
    mkdir $tdir or die $!; 
    system qw/ mplayer -nosound -frames 1 -vf tfields=2 -sstep 3 -vo /, 
      "jpeg:outdir=$tdir", qw/  -vf scale=200:160  /, $file;
    $? == 0 or die "mplayer failed";
    my @jpgs = glob "$tdir/*.jpg";
    scalar(@jpgs) == 1 or die "not exactly one frame, wtf\n";
    rename shift(@jpgs), $out or die $!;
    rmdir $tdir or die $!;
  } else { 
    my $ident = `identify "$file"`;
    $? == 0 or die "identify failed\n";

    my ($w, $h) = $ident =~ /(\d+)x(\d+)/; 

    if ( ($w/$divw) > ($h/$divh) ) {
      #print "w\n";
      exec "convert", "-resize", $divw, $file, $out;
    } else {
      #print "h\n";
      exec "convert", "-resize", "x$divh", $file, $out;
    }
  }
}






