#!/usr/bin/perl -w 

use File::Spec::Functions;
use Getopt::Long;
use Data::Dumper;
use IPC::Run qw/run/; 

Getopt::Long::Configure ("bundling");

my $max = '600m';
my $outdir; 

GetOptions ("outdir|o=s" => \$outdir,
            "volume-size|s=s" => \$max);

my @outdir;
push @outdir, $outdir if defined $outdir; 


if ($max =~ /^ (\d+(\.\d+)?) m $/xi) {
  $max = int($1 * 1024);
}
if ($max =~ /^ (\d+(\.\d+)?) g $/xi) {
  $max = int($1 * 1024 * 1024);
}
if ($max =~ /^ (\d+) k $/xi) {
  $max = $1;
}
unless ($max =~ /^ (\d+) $/xi) {
  die "i don't understand the size $max\n";
}

die "i need a target directory\n" unless @ARGV;
my $toptarget = shift;
die "wtf\n" if @ARGV;

die "$toptarget not a directory\n" unless -d $toptarget;




our $cursize;
our $curvolfh;
our $curvolindex = 0;

sub newvol {
  $curvolindex++;
  close $curvolfh if defined $curvolfh;
  my $of = catfile(@outdir, "vol_$curvolindex");
  open $curvolfh, ">",  $of or die "couldn't open $of : $!\n";
  $cursize = 0; 
}

sub take {
  my ($target, $size) = @_;
  print $curvolfh $target, "\n";
  $cursize += $size;  
}

sub traverse {
  my @target = @_ ;
  my $targetpath = catfile($toptarget, @target); 
  opendir my $dh, $targetpath or die "can't opendir $targetpath: $!\n";
  for my $thing (readdir $dh) {
    next if $thing eq '.';
    next if $thing eq '..';
    my $duout;
    $thing = catfile(@target,$thing);
    $thingpath = catfile($toptarget, $thing);
    -f $thingpath or -d $thingpath or die "wtf is $thingpath\n";
    run [qw/du -sk /, $thingpath], '>', \$duout or die "du returned $?\n";
    $duout =~ /^ \s* (\d+) \s /x or die "bad du output: $duout\n";
    my $thingsize = $1;
    if ($thingsize + $cursize < $max) {
      take $thing, $thingsize;
    } elsif (-f $thingpath) {
      die "$thingpath is too big\n" if ($thingsize > $max);
      newvol;
      take $thing, $thingsize;
    } else {
      &traverse ($thing);
    }
  }
  close $dh;
}

newvol;
traverse; 


